version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitwatch_web_1
      APP_PORT: 3117

  web:
    image: ghcr.io/zapomatic/bitwatch:v0.1.0@sha256:8c99277236b2ba54774ebd6643e4258d020f97d19e21617ff76a11bd40274fd3
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/server/data