version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitwatch_web_1
      APP_PORT: 3117

  web:
    image: ghcr.io/zapomatic/bitwatch:v1.5.1@sha256:86eda8336b1c12197fc7432fa354a7e0936c92e9bd68ff2391458f7971066d71
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/server/data
