version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitwatch_web_1
      APP_PORT: 3117

  web:
    image: ghcr.io/zapomatic/bitwatch:v1.6.2@sha256:9842365054549aa94d2980f2ba77693f683a0e69bae467a4f73ae5110a7b3b7a
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/server/data
