version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitwatch_web_1
      APP_PORT: 3117

  web:
    image: ghcr.io/zapomatic/bitwatch:v1.6.3@sha256:99b8d76be203d7cd78414105c516eb998ff61e26b28ddb98be16c600409f24e8
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/server/data
