version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bitwatch_web_1
      APP_PORT: 3117

  web:
    image: ghcr.io/zapomatic/bitwatch:v1.6.8@sha256:d8bf05ea7df2a3412da25a65b8070800586419884ea843e3253cb0bcac1cf053
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/server/data
